# Generated by Django 5.2.14 on 2026-06-02 17:33

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('slug', models.SlugField(blank=True, max_length=120, unique=True)),
                ('icon', models.CharField(blank=True, help_text="Bootstrap icon class name, e.g., 'bi-cup-hot', 'bi-egg-fried'", max_length=50)),
                ('order_index', models.PositiveIntegerField(default=0, help_text='Used for ordering categories in navigation and menus.')),
            ],
            options={
                'verbose_name': 'Category',
                'verbose_name_plural': 'Categories',
                'ordering': ['order_index', 'name'],
            },
        ),
        migrations.CreateModel(
            name='ComboOffer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(help_text='e.g. Porotta + Beef Curry + Tea', max_length=150)),
                ('description', models.TextField(help_text='Details about what is included in the offer.')),
                ('original_price', models.DecimalField(blank=True, decimal_places=2, help_text='Optional original price in SAR to show savings.', max_digits=6, null=True)),
                ('special_price', models.DecimalField(decimal_places=2, help_text='Offer price in SAR.', max_digits=6)),
                ('image', models.ImageField(blank=True, null=True, upload_to='combos/')),
                ('is_available', models.BooleanField(default=True, verbose_name='Available')),
            ],
            options={
                'verbose_name': 'Combo Offer',
                'verbose_name_plural': 'Combo Offers',
            },
        ),
        migrations.CreateModel(
            name='ContactMessage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('phone', models.CharField(max_length=20)),
                ('email', models.EmailField(blank=True, max_length=254, null=True)),
                ('message', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('is_read', models.BooleanField(default=False)),
            ],
            options={
                'verbose_name': 'Contact Message',
                'verbose_name_plural': 'Contact Messages',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='GalleryItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('image', models.ImageField(upload_to='gallery/')),
                ('category', models.CharField(choices=[('Interior', 'Restaurant Interior'), ('Food', 'Food Photography'), ('Dining', 'Customer Dining Experience'), ('Signature', 'Signature Kerala Dishes')], max_length=20)),
                ('caption', models.CharField(blank=True, help_text='Optional short caption.', max_length=200)),
            ],
            options={
                'verbose_name': 'Gallery Item',
                'verbose_name_plural': 'Gallery Items',
            },
        ),
        migrations.CreateModel(
            name='Review',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('customer_name', models.CharField(max_length=100)),
                ('rating', models.PositiveIntegerField(help_text='Rating from 1 to 5 stars', validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)])),
                ('review_text', models.TextField()),
                ('is_approved', models.BooleanField(default=True, help_text='Approve this review to display it on the website.')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Customer Review',
                'verbose_name_plural': 'Customer Reviews',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='SpecialItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150)),
                ('description', models.TextField(blank=True)),
                ('price', models.DecimalField(decimal_places=2, help_text='Price in SAR.', max_digits=6)),
                ('image', models.ImageField(blank=True, null=True, upload_to='specials/')),
                ('is_available', models.BooleanField(default=True, verbose_name='Available')),
                ('category_group', models.CharField(choices=[('Fish Specials', 'Fish Specials'), ('Mutton Specials', 'Mutton Specials'), ('Beef Specials', 'Beef Specials'), ('Chicken Specials', 'Chicken Specials')], max_length=30)),
                ('order_index', models.PositiveIntegerField(default=0)),
            ],
            options={
                'verbose_name': "Today's Special Item",
                'verbose_name_plural': "Today's Special Items",
                'ordering': ['category_group', 'order_index', 'name'],
            },
        ),
        migrations.CreateModel(
            name='MenuItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150)),
                ('description', models.TextField(blank=True, help_text='Brief description of ingredients or preparation.')),
                ('price', models.DecimalField(decimal_places=2, help_text='Price in SAR (Saudi Riyal).', max_digits=6)),
                ('image', models.ImageField(blank=True, null=True, upload_to='menu_items/')),
                ('is_available', models.BooleanField(default=True, verbose_name='Available')),
                ('is_vegetarian', models.BooleanField(default=False, verbose_name='Vegetarian')),
                ('is_spicy', models.BooleanField(default=False, verbose_name='Spicy')),
                ('order_index', models.PositiveIntegerField(default=0)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='restaurant.category')),
            ],
            options={
                'verbose_name': 'Menu Item',
                'verbose_name_plural': 'Menu Items',
                'ordering': ['category', 'order_index', 'name'],
            },
        ),
    ]
